<template>
	<div>
		<div id="timer">
			<Stopwatch
				:timer="timerValue"
				:playable="playable"
				@time-up="timesUp"
				:key="timerKey"
			></Stopwatch>
		</div>

		<h1 class="gameHeader">Tic Tac Toe</h1>

		<div class="gamearea">
			<div class="board">
				<div class="gameTopbar">
					<span id="restart" @click="restartGame">&#8635;</span>
					<div v-if="isGameOver">
						<p class="win" v-if="isDraw">Match is Tied</p>
						<p class="win" v-else>{{ getWinnerName }} wins</p>
					</div>
					<div v-else>
						<p class="active">{{ getTurnUser }}'s turn</p>
					</div>
				</div>

				<GameBoard
					:N="N"
					:turnNo="turn"
					:isMultiplayer="isMultiplayer"
					:turnComplete="turnComplete"
					:playable="playable"
					:handleWinner="handleWinner"
					:setMultiplayerPlayerNo="setMultiplayerPlayerNo"
					:key="boardKey"
					@game-id="setGameId"
					@multiplayer-filled="startMultiplayerGame"
					@multiplayer-move-fn="setMultiplayerFn"
					@player-move="setMultiplayerMove"
				></GameBoard>
			</div>
		</div>
		<div class="gameinfo">
			<p>
				{{ participators[0] }} (X):
				<span id="player1wins">{{ player1wins }}</span>
			</p>
			<p>
				{{ participators[1] }} (O):
				<span id="player2wins">{{ player2wins }}</span>
			</p>
		</div>
	</div>
</template>

<script setup>
	import { ref, onMounted, computed } from "vue";
	import { useRequestStore } from "@/stores/request";

	const request = useRequestStore();

	import Stopwatch from "@/components/Stopwatch.vue";
	import GameBoard from "@/components/GameBoard.vue";

	const socket = ref();

	const playerName = ref("");
	const N = ref(3); // Board size
	const player1wins = ref(0);
	const player2wins = ref(0);
	const timerValue = ref(15); // Stopwatch timer
	const isGameOver = ref(false);
	const isDraw = ref(false);
	const isPlaying = ref(false);
	const isMultiplayer = ref(false);
	const multiplayerPlayerNo = ref(0); // Which player in the multiplayer game is it
	const turn = ref(1); // Which player's turn is it
	const winner = ref(0);
	const winnerName = ref("");
	const participators = ref(["Player 1", "Player 2"]);

	const getWinnerName = computed(() => {
		if (winner.value != 0 && winnerName.value == "")
			return "Player " + winner.value;
		else return winnerName.value;
	});

	const getTurnUser = computed(() => {
		return participators.value[turn.value - 1];
	});

	const move = ref(1); // No. of moves passed
	const steps = ref([]); // Stores each move in the game

	const boardKey = ref(0); // Reference to game board component
	const timerKey = ref(0); // Reference to stopwatch component

	const gameID = ref(); // Unique game ID generated by server for multiplayer

	let multiplayerMoveFn = null; // Function from game board component to handle when opponent has given a move

	const turnComplete = (nextTurn) => {
		turn.value = nextTurn;
		move.value++;
		timerKey.value++;
	};

	const playable = () => {
		return isPlaying.value && !isGameOver.value;
	};

	const timesUp = () => {
		turn.value = turn.value == 1 ? 2 : 1;
		handleWinner();
	};

	const setGameId = (id) => {
		gameID.value = id;
	};

	const handleWinner = (currentMove) => {
		if (!playable()) return;

		isGameOver.value = true;
		isPlaying.value = false;

		isDraw.value = currentMove ? currentMove.isDraw : false;

		const winningPlayer = currentMove
			? currentMove.winnerData.winner
			: turn.value;
		winnerName.value = currentMove
			? currentMove.winnerData.winnerName
			: participators.value[turn.value - 1];

		if (winningPlayer == 1) player1wins.value++;
		else if (winningPlayer == 2) player2wins.value++;

		winner.value = winningPlayer;

		if (!isMultiplayer.value) return;

		socket.value.send(
			JSON.stringify({
				id: gameID.value,
				type: "WINNER",
				isdraw: isDraw.value,
				winner: winningPlayer,
				winnerName: winnerName.value,
			})
		);
	};

	const removeGame = async () => {
		request.get("/game/remove?id=" + gameID.value);
	};

	// Check if the game is a multiplayer game
	// gameType == 0 : SINGLE PLAYER
	// gameType == 1 : MULTIPLAYER
	// Sets up the websocket if it's multiplayer
	const checkMultiplayer = async () => {
		const url = new URL(window.location.href);
		const searchParams = url.searchParams;
		const gameType = searchParams.get("gametype");

		if (gameType == 1) {
			isMultiplayer.value = true;
			isPlaying.value = false;
			// boardKey.value++;

			const sock = await import("@/utils/websocket.js");
			socket.value = sock.socket;
			setupSockets();
			askForName();
		}
	};

	const startMultiplayerGame = async () => {
		// Check if the socket is ready
		const interval = setInterval(() => {
			if (socket.value.readyState) {
				socket.value.send(
					JSON.stringify({
						id: gameID.value,
						type: "START",
					})
				);
				isPlaying.value = true;
				setUserName(playerName.value);
				clearInterval(interval);
			}
		}, 100);
	};

	const setMultiplayerFn = (fn) => {
		multiplayerMoveFn = fn;
	};

	const setMultiplayerPlayerNo = (no) => {
		multiplayerPlayerNo.value = no;
	};

	const setMultiplayerMove = (move) => {
		socket.value.send(
			JSON.stringify({
				id: gameID.value,
				type: "MOVE",
				data: move,
			})
		);
	};

	const restartGame = () => {
		isGameOver.value = false;
		isDraw.value = false;
		isPlaying.value = true;

		winner.value = 0;
		turn.value = 1;
		move.value = 1;

		boardKey.value++;
		timerKey.value++;
	};

	const setupSockets = () => {
		socket.value.onmessage = function (event) {
			const data = JSON.parse(event.data);

			if (data.type == "START" && data.id == gameID.value) {
				console.log("GAME CAN START NOWWWW!!!!");
				isPlaying.value = true;
				setUserName(playerName.value);
			} else if (data.type == "MOVE") {
				multiplayerMoveFn(data.data);
			} else if (data.type == "WINNER") {
				handleWinner({
					isDraw: data.isdraw,
					winnerData: {
						winner: data.winner,
						winnerName: data.winnerName,
					},
				});
			}
		};
	};

	// Asks user for name during multiplayer game
	const askForName = () => {
		const name = prompt("Enter your name");

		if (name) {
			playerName.value = name;
		}
	};

	const setUserName = async (name) => {
		return request.post("/game/name", {
			id: gameID.value,
			name: name,
			playerNo: multiplayerPlayerNo.value,
		});
	};

	onMounted(() => {
		restartGame();
		checkMultiplayer();
	});

	// Remove the game instance from server if user is leaving
	// In case of multiplayer, only the host can remove
	window.onbeforeunload = function () {
		if (
			!isMultiplayer.value ||
			(isMultiplayer.value && multiplayerPlayerNo.value == 1)
		)
			removeGame();
	};
</script>

<style scoped>
	.gameHeader {
		text-align: center;
		margin-block: 1rem;
	}

	.gameTopbar {
		height: 32px;
		margin-block: 0.5rem;

		div {
			width: 93%;
			display: inline-block;
		}

		#restart {
			cursor: pointer;
			font-size: 1.25rem;
			font-weight: 700;
			font-family: "Lucida Sans Unicode";
		}
		#restart:hover {
			opacity: 0.5;
		}

		p {
			text-align: center;
			font-size: 1.25rem;
		}
		p.active {
			font-weight: 500;
			color: #6c5ce7;
		}
		p.win {
			font-weight: 700;
			color: #00b894;
		}
	}

	.gamearea {
		display: flex;
		justify-content: center;
		align-items: center;
		margin-top: 2rem;
	}

	.gameinfo {
		margin-top: 2rem;
		p {
			text-align: center;
			font-size: 1.5rem;
		}
	}

	::backdrop {
		background-color: rgb(0, 0, 0, 0.65);
		height: 100%;
	}
	dialog {
		width: 400px;
		height: 165px;
		outline: none;
		border: none;
		margin: auto;
		font-size: 1.5rem;
		text-align: center;
	}

	.btn {
		outline: none;
		border: none;
		cursor: pointer;
		width: 100px;
		height: 36px;
		margin-block: 1rem;
	}

	.btn-primary {
		background-color: #6c5ce7;
		color: white;
	}

	.btn-outline {
		background-color: transparent;
		border: 1px solid #333;
	}

	.button-group {
		display: flex;
		gap: 1rem;
		justify-content: center;
	}
</style>
